name: Build deploy eureka

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean compile package -DskipTests 
    - name: Copy Artifact via scp to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "./target/discovery-service-0.0.1-SNAPSHOT.jar"
        target: "/root/static/"

    - name: Executing remote command to run the service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: "root"
        PORT: "22"
        KEY: ${{ secrets.KEY }}
        envs:
          DBPass:${{ secrets.DBPASSDEV }}
        #script_stop: true
        script: |
         lsof -i :8761
         kill $(lsof -t -i:8761)
         cd /root/static/target
         nohup java -jar discovery-service-0.0.1-SNAPSHOT.jar > eureka-server.log &
         netstat -lnput
